# Generated by Django 5.1.7 on 2025-03-15 20:32

import crimsonslate_portfolio.validators
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('emoji', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[crimsonslate_portfolio.validators.validate_emoji])),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('desc', models.TextField(blank=True, default=None, max_length=2048, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_image', models.BooleanField(blank=True, editable=False, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='source_media', to='filer.file')),
                ('tags', models.ManyToManyField(blank=True, default=None, to='crimsonslate_portfolio.mediatag')),
            ],
            options={
                'ordering': ['-date_created'],
                'constraints': [models.UniqueConstraint(fields=('title', 'slug'), name='crimsonslate_portfolio_media_unique_title_and_slug')],
            },
        ),
    ]
